python -m graphphysics.train \
            --training_parameters_path=training_config/aneurysm-4Dflow.json \
            --num_epochs=5 \
            --init_lr=0.001 \
            --batch_size=1 \
            --warmup=500 \
            --num_workers=0 \
            --prefetch_factor=0 \
            --model_save_name=model \
            --no_edge_feature \
            --use_previous_data=false
