name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.4.0
        pip install numpy==2.1.2
        pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-2.4.0+cpu.html
        pip install torch-sparse      -f https://pytorch-geometric.com/whl/torch-2.4.0+cpu.html
        pip install torch-cluster     -f https://pytorch-geometric.com/whl/torch-2.4.0+cpu.html
        pip install torch-spline-conv  -f https://pytorch-geometric.com/whl/torch-2.4.0+cpu.html
        pip install torch-geometric
        pip install loguru==0.7.2
        pip install autoflake==2.3.0
        pip install pytest==8.0.1
        pip install meshio==5.3.5
        pip install h5py==3.13.0
        pip install pyvista
        pip install lightning
        pip install pytest-benchmark
        pip install pylint
        pip install black
        pip install wandb
        pip install absl-py
        pip install "wandb[media]"
        pip install panel
    - name: Linting code
      run: |
        make lint
    - name: Testing code
      run: |
        make test-gp
    - name: Train & Predict Pipeline
      env:
        WANDB_MODE: offline
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        python -c "import panel as pn; pn.extension('vtk')"
        make train-predict
